### ISSUE TITLE
struct.error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by nizhuan-jjr** [NueCD/motion.py#1]
![0](https://user-images.githubusercontent.com/3255986/222469709-8a88b63b-f580-471d-882f-e6a7f02152c0.png)

This is the vmd file.
[input.zip](https://github.com/nuekaze/VMD-motion-extract/files/10872710/input.zip)

**Comment by nuekaze** [comment]
I found some issues with the name decoding and it is fixed now. Before it only read utf-8 and shift-jis (japanese) but your model was chinese encoding. Now I use some autodetect that should work better.
